---
- hosts: etcd
  pre_tasks:
    - name: Update apt cache on Debian based systems
      apt: update_cache=yes cache_valid_time=3600
      when: ansible_os_family == "Debian"
    - name: Install prerequisite packages for docker_facts module
      package: name={{ item }}
      with_items:
        - curl
        - iproute
    - name: Execute docker_facts module
      docker_facts:
  roles:
    - role: ansible-etcd
      etcd_interface: eth0
