---
- hosts: all
  pre_tasks:
    - name: Install prerequisite packages for facts
      package: name={{ item }}
      with_items:
        - iproute
    - name: Install prerequisite packages for tests
      package: name={{ item }}
      with_items:
        - curl
    - name: Gather facts now that prerequisite packages are installed
      setup: filter=ansible_*
  roles:
    - role: ansible-etcd
      etcd_interface: eth0
