---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: ansible-lint
platforms:
  - name: etcd-01
    image: retr0h/centos7-systemd-ansible
    image_version: latest
    privileged: True
    command: /usr/sbin/init
    groups:
      - etcd
  - name: etcd-02
    image: retr0h/centos7-systemd-ansible
    image_version: latest
    privileged: True
    command: /usr/sbin/init
    groups:
      - etcd
  - name: etcd-03
    image: retr0h/centos7-systemd-ansible
    image_version: latest
    privileged: True
    command: /usr/sbin/init
    groups:
      - etcd
verifier:
  name: testinfra
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
